services:
  - type: web
    name: extract-img-api
    env: python
    plan: free
    buildCommand: |
      cd extract-img-api
      pip install -r requirements.txt
    startCommand: |
      cd extract-img-api && uvicorn extract_img:app --host 0.0.0.0 --port $PORT
